# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='BWARP',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='FRAA',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='Tav',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='VORP',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
