# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0002_auto_20171023_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='league',
            field=models.CharField(default='MLB', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='BWARP',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='player',
            name='FRAA',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='player',
            name='Tav',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='player',
            name='VORP',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=4),
        ),
    ]
