# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0007_remove_picture_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
