# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0010_auto_20171024_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
