# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0013_auto_20171108_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
