# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0014_auto_20171108_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
