# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0016_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
