# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0017_auto_20171108_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, default='Machine Learning', max_length=300),
            preserve_default=False,
        ),
    ]
