# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0019_auto_20171108_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, default=0, max_length=300),
            preserve_default=False,
        ),
    ]
