# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0020_auto_20171108_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
