# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0025_project_calculations'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proj_image',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
