# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0026_project_proj_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chart', models.FileField(blank=True, null=True, upload_to='media')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlb.Project')),
            ],
        ),
    ]
