# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0027_projectpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
    ]
