# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0029_auto_20171113_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_image',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='projectpic',
            name='chart',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
    ]
